In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [9]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [10]:
data=data.drop(["RowNumber","CustomerId","Surname"],axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [11]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import pickle

In [12]:
label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"])

In [13]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,1,39,5,0.00,2,1,0,96270.64,0
9996,516,France,1,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,0,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,1,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,0,28,4,130142.79,1,1,0,38190.78,0

In [14]:
from sklearn.preprocessing import OneHotEncoder
one_hot_encoder_geography=OneHotEncoder()
geography_encoding=one_hot_encoder_geography.fit_transform(data[["Geography"]])
geography_encoding

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [15]:
one_hot_encoder_geography.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [16]:
geo_encoded_df=pd.DataFrame(geography_encoding.toarray(),columns=one_hot_encoder_geography.get_feature_names_out(["Geography"]))

In [17]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [18]:
data=pd.concat([data.drop("Geography",axis=1),geo_encoded_df],axis=1)
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [19]:
with open("label_encoder_gender.pkl","wb") as f:
    pickle.dump(label_encoder_gender,f)
with open("one_hot_encoder_geography.pkl","wb") as f:
    pickle.dump(one_hot_encoder_geography,f)

In [20]:
X=data.drop("Exited",axis=1)
y=data["Exited"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [21]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [22]:
with open("scaler.pkl","wb") as f:
    pickle.dump(scaler,f)

In [23]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [ ]:
pip install --upgrade tensorflow keras

Requirement already satisfied: tensorflow in c:\users\kuraa\anaconda3\lib\site-packages (2.15.0)
Collecting tensorflow
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/e3/f8/9246d3c7e185a29d7359d8b12b3d70bf2c3150ecf1427ec1382290e71a56/tensorflow-2.20.0-cp311-cp311-win_amd64.whl.metadata
  Downloading tensorflow-2.20.0-cp311-cp311-win_amd64.whl.metadata (4.6 kB)
Requirement already satisfied: keras in c:\users\kuraa\anaconda3\lib\site-packages (2.15.0)
Collecting keras
  Obtaining dependency information for keras from https://files.pythonhosted.org/packages/28/b5/ea85873abc99dc64a7a27ff1a8dbfdc7dbb57d4e5d1a423abc11217af4f1/keras-3.13.2-py3-none-any.whl.metadata
  Downloading keras-3.13.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (2.1.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Collecting flatbuffers>=24.3.25 (from tensorflow)
  Obtaining dependency information for flatbuffers>=24.3.25 from https://files.pythonhosted.org/packages/e8/2d/d2a548598be01649e2d46231d151a6c56d10b964d94043a335ae56ea2d92/flatbuffers-25.12.19-py2.py3-none-any.whl.metadata
  Downloading flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (16.0.6)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: packaging in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (23.1)
Collecting protobuf>=5.28.0 (from tensorflow)
  Obtaining dependency information for protobuf>=5.28.0 from https://files.pythonhosted.org/packages/cb/71/7c32eaf34a61a1bae1b62a2ac4ffe09b8d1bb0cf93ad505f42040023db89/protobuf-7.34.0-cp310-abi3-win_amd64.whl.metadata
  Downloading protobuf-7.34.0-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (68.0.0)
Requirement already satisfied: six>=1.12.0 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (1.16.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (4.7.1)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (1.14.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorflow) (1.60.1)
Collecting tensorboard~=2.20.0 (from tensorflow)
  Obtaining dependency information for tensorboard~=2.20.0 from https://files.pythonhosted.org/packages/9c/d9/a5db55f88f258ac669a92858b70a714bbbd5acd993820b41ec4a96a4d77f/tensorboard-2.20.0-py3-none-any.whl.metadata
  Downloading tensorboard-2.20.0-py3-none-any.whl.metadata (1.8 kB)
Collecting numpy>=1.26.0 (from tensorflow)
  Obtaining dependency information for numpy>=1.26.0 from https://files.pythonhosted.org/packages/76/ae/e0265e0163cf127c24c3969d29f1c4c64551a1e375d95a13d32eab25d364/numpy-2.4.2-cp311-cp311-win_amd64.whl.metadata
  Downloading numpy-2.4.2-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Collecting h5py>=3.11.0 (from tensorflow)
  Obtaining dependency information for h5py>=3.11.0 from https://files.pythonhosted.org/packages/23/95/499b4e56452ef8b6c95a271af0dde08dac4ddb70515a75f346d4f400579b/h5py-3.15.1-cp311-cp311-win_amd64.whl.metadata
  Downloading h5py-3.15.1-cp311-cp311-win_amd64.whl.metadata (3.1 kB)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Obtaining dependency information for ml_dtypes<1.0.0,>=0.5.1 from https://files.pythonhosted.org/packages/b4/24/70bd59276883fdd91600ca20040b41efd4902a923283c4d6edcb1de128d2/ml_dtypes-0.5.4-cp311-cp311-win_amd64.whl.metadata
  Downloading ml_dtypes-0.5.4-cp311-cp311-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: rich in c:\users\kuraa\anaconda3\lib\site-packages (from keras) (13.9.4)
Collecting namex (from keras)
  Obtaining dependency information for namex from https://files.pythonhosted.org/packages/b2/bc/465daf1de06409cdd4532082806770ee0d8d7df434da79c76564d0f69741/namex-0.1.0-py3-none-any.whl.metadata
  Downloading namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras)
  Obtaining dependency information for optree from https://files.pythonhosted.org/packages/d9/13/ee6a65060edde25517151eff8a9e1468e6fd65054fabd14a441161eeafd6/optree-0.19.0-cp311-cp311-win_amd64.whl.metadata
  Downloading optree-0.19.0-cp311-cp311-win_amd64.whl.metadata (35 kB)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\kuraa\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.38.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\kuraa\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\kuraa\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\kuraa\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kuraa\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2025.1.31)
Requirement already satisfied: markdown>=2.6.8 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.4.1)
Requirement already satisfied: pillow in c:\users\kuraa\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (10.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\kuraa\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (2.2.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\kuraa\anaconda3\lib\site-packages (from rich->keras) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\kuraa\anaconda3\lib\site-packages (from rich->keras) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\kuraa\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\kuraa\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (2.1.1)
Downloading tensorflow-2.20.0-cp311-cp311-win_amd64.whl (331.8 MB)
   ---------------------------------------- 0.0/331.8 MB ? eta -:--:--
   ---------------------------------------- 1.7/331.8 MB 37.4 MB/s eta 0:00:09
   ---------------------------------------- 2.2/331.8 MB 34.7 MB/s eta 0:00:10
   ---------------------------------------- 2.7/331.8 MB 21.4 MB/s eta 0:00:16
   ---------------------------------------- 3.3/331.8 MB 17.4 MB/s eta 0:00:19
   ---------------------------------------- 3.9/331.8 MB 19.0 MB/s eta 0:00:18
   ---------------------------------------- 3.9/331.8 MB 19.0 MB/s eta 0:00:18
    --------------------------------------- 4.6/331.8 MB 14.0 MB/s eta 0:00:24
    --------------------------------------- 5.9/331.8 MB 16.5 MB/s eta 0:00:20
    --------------------------------------- 6.4/331.8 MB 15.7 MB/s eta 0:00:21
    --------------------------------------- 7.1/331.8 MB 15.1 MB/s eta 0:00:22
    --------------------------------------- 7.5/331.8 MB 15.0 MB/s eta 0:00:22
    --------------------------------------- 8.3/331.8 MB 14.7 MB/s eta 0:00:22
   - -------------------------------------- 8.7/331.8 MB 14.7 MB/s eta 0:00:22
   - -------------------------------------- 9.2/331.8 MB 14.0 MB/s eta 0:00:23
   - -------------------------------------- 9.6/331.8 MB 13.6 MB/s eta 0:00:24
   - -------------------------------------- 10.0/331.8 MB 13.4 MB/s eta 0:00:25
   - -------------------------------------- 10.4/331.8 MB 13.1 MB/s eta 0:00:25
   - -------------------------------------- 10.8/331.8 MB 12.8 MB/s eta 0:00:26
   - -------------------------------------- 11.2/331.8 MB 12.3 MB/s eta 0:00:26
   - -------------------------------------- 11.6/331.8 MB 11.7 MB/s eta 0:00:28
   - -------------------------------------- 11.9/331.8 MB 11.1 MB/s eta 0:00:29
   - -------------------------------------- 12.4/331.8 MB 10.7 MB/s eta 0:00:30
   - -------------------------------------- 12.8/331.8 MB 10.9 MB/s eta 0:00:30
   - -------------------------------------- 13.1/331.8 MB 10.4 MB/s eta 0:00:31
   - -------------------------------------- 13.4/331.8 MB 10.2 MB/s eta 0:00:32
   - -------------------------------------- 13.8/331.8 MB 10.1 MB/s eta 0:00:32
   - -------------------------------------- 14.2/331.8 MB 10.6 MB/s eta 0:00:31
   - -------------------------------------- 14.7/331.8 MB 10.2 MB/s eta 0:00:32
   - -------------------------------------- 15.2/331.8 MB 10.2 MB/s eta 0:00:31
   - -------------------------------------- 15.4/331.8 MB 9.8 MB/s eta 0:00:33
   - -------------------------------------- 15.6/331.8 MB 9.4 MB/s eta 0:00:34
   - -------------------------------------- 16.0/331.8 MB 9.0 MB/s eta 0:00:36
   - -------------------------------------- 16.4/331.8 MB 9.0 MB/s eta 0:00:36
   -- ------------------------------------- 16.9/331.8 MB 8.8 MB/s eta 0:00:36
   -- ------------------------------------- 17.5/331.8 MB 8.8 MB/s eta 0:00:36
   -- ------------------------------------- 18.2/331.8 MB 8.8 MB/s eta 0:00:36
   -- ------------------------------------- 18.7/331.8 MB 9.0 MB/s eta 0:00:35
   -- ------------------------------------- 19.5/331.8 MB 9.1 MB/s eta 0:00:35
   -- ------------------------------------- 20.2/331.8 MB 9.4 MB/s eta 0:00:34
   -- ------------------------------------- 20.8/331.8 MB 9.6 MB/s eta 0:00:33
   -- ------------------------------------- 21.6/331.8 MB 10.1 MB/s eta 0:00:31
   -- ------------------------------------- 22.1/331.8 MB 10.2 MB/s eta 0:00:31
   -- ------------------------------------- 22.7/331.8 MB 10.4 MB/s eta 0:00:30
   -- ------------------------------------- 23.4/331.8 MB 11.1 MB/s eta 0:00:28
   -- ------------------------------------- 24.1/331.8 MB 11.9 MB/s eta 0:00:26
   --- ------------------------------------ 25.0/331.8 MB 12.1 MB/s eta 0:00:26
   --- ------------------------------------ 25.6/331.8 MB 12.4 MB/s eta 0:00:25
   --- ------------------------------------ 26.3/331.8 MB 13.6 MB/s eta 0:00:23
   --- ------------------------------------ 27.2/331.8 MB 14.6 MB/s eta 0:00:21
   --- ------------------------------------ 27.6/331.8 MB 14.2 MB/s eta 0:00:22
   --- ------------------------------------ 28.3/331.8 MB 14.2 MB/s eta 0:00:22
   --- ------------------------------------ 28.9/331.8 MB 14.6 MB/s eta 0:00:21
   --- ------------------------------------ 29.4/331.8 MB 14.2 MB/s eta 0:00:22
   --- ------------------------------------ 29.7/331.8 MB 13.9 MB/s eta 0:00:22
   --- ------------------------------------ 30.3/331.8 MB 13.4 MB/s eta 0:00:23
   --- ------------------------------------ 30.9/331.8 MB 13.4 MB/s eta 0:00:23
   --- ------------------------------------ 31.1/331.8 MB 13.4 MB/s eta 0:00:23
   --- ------------------------------------ 32.0/331.8 MB 13.1 MB/s eta 0:00:23
   --- ------------------------------------ 32.5/331.8 MB 13.1 MB/s eta 0:00:23
   --- ------------------------------------ 33.0/331.8 MB 12.8 MB/s eta 0:00:24
   ---- ----------------------------------- 33.4/331.8 MB 12.8 MB/s eta 0:00:24
   ---- ----------------------------------- 34.1/331.8 MB 12.8 MB/s eta 0:00:24
   ---- ----------------------------------- 34.6/331.8 MB 12.6 MB/s eta 0:00:24
   ---- ----------------------------------- 35.2/331.8 MB 12.4 MB/s eta 0:00:25
   ---- ----------------------------------- 35.7/331.8 MB 11.9 MB/s eta 0:00:25
   ---- ----------------------------------- 36.2/331.8 MB 11.7 MB/s eta 0:00:26
   ---- ----------------------------------- 36.8/331.8 MB 11.7 MB/s eta 0:00:26
   ---- ----------------------------------- 37.3/331.8 MB 11.7 MB/s eta 0:00:26
   ---- ----------------------------------- 37.9/331.8 MB 11.7 MB/s eta 0:00:26
   ---- ----------------------------------- 38.6/331.8 MB 11.7 MB/s eta 0:00:26
   ---- ----------------------------------- 39.3/331.8 MB 11.9 MB/s eta 0:00:25
   ---- ----------------------------------- 39.9/331.8 MB 12.1 MB/s eta 0:00:25
   ---- ----------------------------------- 40.3/331.8 MB 12.1 MB/s eta 0:00:25
   ---- ----------------------------------- 40.9/331.8 MB 11.9 MB/s eta 0:00:25
   ---- ----------------------------------- 41.2/331.8 MB 11.9 MB/s eta 0:00:25
   ----- ---------------------------------- 41.7/331.8 MB 11.7 MB/s eta 0:00:25
   ----- ---------------------------------- 42.2/331.8 MB 11.3 MB/s eta 0:00:26
   ----- ---------------------------------- 42.8/331.8 MB 11.7 MB/s eta 0:00:25
   ----- ---------------------------------- 43.5/331.8 MB 11.9 MB/s eta 0:00:25
   ----- ---------------------------------- 44.2/331.8 MB 12.1 MB/s eta 0:00:24
   ----- ---------------------------------- 44.9/331.8 MB 12.4 MB/s eta 0:00:24
   ----- ---------------------------------- 45.5/331.8 MB 12.4 MB/s eta 0:00:24
   ----- ---------------------------------- 46.1/331.8 MB 12.6 MB/s eta 0:00:23
   ----- ---------------------------------- 46.3/331.8 MB 11.9 MB/s eta 0:00:24
   ----- ---------------------------------- 46.9/331.8 MB 12.1 MB/s eta 0:00:24
   ----- ---------------------------------- 47.4/331.8 MB 11.9 MB/s eta 0:00:24
   ----- ---------------------------------- 48.2/331.8 MB 12.4 MB/s eta 0:00:23
   ----- ---------------------------------- 48.9/331.8 MB 12.6 MB/s eta 0:00:23
   ----- ---------------------------------- 49.6/331.8 MB 12.4 MB/s eta 0:00:23
   ------ --------------------------------- 50.2/331.8 MB 12.4 MB/s eta 0:00:23
   ------ --------------------------------- 50.9/331.8 MB 12.8 MB/s eta 0:00:22
   ------ --------------------------------- 51.5/331.8 MB 13.1 MB/s eta 0:00:22
   ------ --------------------------------- 52.2/331.8 MB 13.4 MB/s eta 0:00:21
   ------ --------------------------------- 52.9/331.8 MB 13.6 MB/s eta 0:00:21
   ------ --------------------------------- 53.3/331.8 MB 13.1 MB/s eta 0:00:22
   ------ --------------------------------- 53.4/331.8 MB 12.6 MB/s eta 0:00:23
   ------ --------------------------------- 54.1/331.8 MB 12.6 MB/s eta 0:00:23
   ------ --------------------------------- 54.9/331.8 MB 12.6 MB/s eta 0:00:23
   ------ --------------------------------- 55.7/331.8 MB 12.4 MB/s eta 0:00:23
   ------ --------------------------------- 56.3/331.8 MB 12.4 MB/s eta 0:00:23
   ------ --------------------------------- 57.1/331.8 MB 13.4 MB/s eta 0:00:21
   ------ --------------------------------- 57.4/331.8 MB 13.1 MB/s eta 0:00:21
   ------ --------------------------------- 58.1/331.8 MB 13.1 MB/s eta 0:00:21
   ------- -------------------------------- 58.9/331.8 MB 13.1 MB/s eta 0:00:21
   ------- -------------------------------- 59.6/331.8 MB 13.4 MB/s eta 0:00:21
   ------- -------------------------------- 60.4/331.8 MB 13.4 MB/s eta 0:00:21
   ------- -------------------------------- 61.0/331.8 MB 13.4 MB/s eta 0:00:21
   ------- -------------------------------- 61.6/331.8 MB 13.4 MB/s eta 0:00:21
   ------- -------------------------------- 62.0/331.8 MB 12.8 MB/s eta 0:00:22
   ------- -------------------------------- 62.1/331.8 MB 12.1 MB/s eta 0:00:23
   ------- -------------------------------- 62.3/331.8 MB 12.1 MB/s eta 0:00:23
   ------- -------------------------------- 63.0/331.8 MB 11.9 MB/s eta 0:00:23
   ------- -------------------------------- 64.0/331.8 MB 13.1 MB/s eta 0:00:21
   ------- -------------------------------- 64.4/331.8 MB 13.1 MB/s eta 0:00:21
   ------- -------------------------------- 65.2/331.8 MB 12.8 MB/s eta 0:00:21
   ------- -------------------------------- 66.0/331.8 MB 13.1 MB/s eta 0:00:21
   -------- ------------------------------- 66.7/331.8 MB 13.4 MB/s eta 0:00:20
   -------- ------------------------------- 67.7/331.8 MB 13.9 MB/s eta 0:00:19
   -------- ------------------------------- 68.1/331.8 MB 13.6 MB/s eta 0:00:20
   -------- ------------------------------- 68.8/331.8 MB 13.6 MB/s eta 0:00:20
   -------- ------------------------------- 69.3/331.8 MB 13.1 MB/s eta 0:00:21
   -------- ------------------------------- 69.6/331.8 MB 12.6 MB/s eta 0:00:21
   -------- ------------------------------- 70.1/331.8 MB 12.4 MB/s eta 0:00:22
   -------- ------------------------------- 70.7/331.8 MB 12.4 MB/s eta 0:00:22
   -------- ------------------------------- 71.3/331.8 MB 12.4 MB/s eta 0:00:22
   -------- ------------------------------- 71.8/331.8 MB 11.9 MB/s eta 0:00:22
   -------- ------------------------------- 72.3/331.8 MB 13.1 MB/s eta 0:00:20
   -------- ------------------------------- 72.8/331.8 MB 13.1 MB/s eta 0:00:20
   -------- ------------------------------- 73.4/331.8 MB 13.1 MB/s eta 0:00:20
   -------- ------------------------------- 74.0/331.8 MB 12.8 MB/s eta 0:00:21
   --------- ------------------------------ 74.7/331.8 MB 13.1 MB/s eta 0:00:20
   --------- ------------------------------ 75.3/331.8 MB 12.8 MB/s eta 0:00:20
   --------- ------------------------------ 75.7/331.8 MB 12.8 MB/s eta 0:00:20
   --------- ------------------------------ 76.1/331.8 MB 12.1 MB/s eta 0:00:22
   --------- ------------------------------ 76.7/331.8 MB 11.9 MB/s eta 0:00:22
   --------- ------------------------------ 77.5/331.8 MB 11.9 MB/s eta 0:00:22
   --------- ------------------------------ 78.3/331.8 MB 11.7 MB/s eta 0:00:22
   --------- ------------------------------ 78.8/331.8 MB 11.9 MB/s eta 0:00:22
   --------- ------------------------------ 79.2/331.8 MB 11.9 MB/s eta 0:00:22
   --------- ------------------------------ 80.0/331.8 MB 12.6 MB/s eta 0:00:20
   --------- ------------------------------ 80.4/331.8 MB 12.1 MB/s eta 0:00:21
   --------- ------------------------------ 81.0/331.8 MB 12.1 MB/s eta 0:00:21
   --------- ------------------------------ 81.4/331.8 MB 11.9 MB/s eta 0:00:22
   --------- ------------------------------ 81.8/331.8 MB 12.1 MB/s eta 0:00:21
   --------- ------------------------------ 82.9/331.8 MB 12.6 MB/s eta 0:00:20
   ---------- ----------------------------- 83.6/331.8 MB 12.8 MB/s eta 0:00:20
   ---------- ----------------------------- 84.4/331.8 MB 13.1 MB/s eta 0:00:19
   ---------- ----------------------------- 85.1/331.8 MB 13.1 MB/s eta 0:00:19
   ---------- ----------------------------- 86.0/331.8 MB 14.2 MB/s eta 0:00:18
   ---------- ----------------------------- 86.6/331.8 MB 13.9 MB/s eta 0:00:18
   ---------- ----------------------------- 87.1/331.8 MB 13.9 MB/s eta 0:00:18
   ---------- ----------------------------- 87.7/331.8 MB 13.9 MB/s eta 0:00:18
   ---------- ----------------------------- 88.4/331.8 MB 13.6 MB/s eta 0:00:18
   ---------- ----------------------------- 89.0/331.8 MB 13.6 MB/s eta 0:00:18
   ---------- ----------------------------- 89.7/331.8 MB 14.2 MB/s eta 0:00:18
   ---------- ----------------------------- 90.0/331.8 MB 13.6 MB/s eta 0:00:18
   ---------- ----------------------------- 90.3/331.8 MB 12.8 MB/s eta 0:00:19
   ---------- ----------------------------- 90.5/331.8 MB 12.8 MB/s eta 0:00:19
   ---------- ----------------------------- 91.0/331.8 MB 12.6 MB/s eta 0:00:20
   ----------- ---------------------------- 91.9/331.8 MB 12.4 MB/s eta 0:00:20

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\kuraa\\anaconda3\\Lib\\site-packages\\~umpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll'
Consider using the `--user` option or check the permissions.

In [24]:
model=Sequential([
    Dense(64,activation="relu",input_shape=(X_train.shape[1],)),
    Dense(32,activation="relu"),
    Dense(1,activation="sigmoid")
    
])

e:\Ann_Classification\venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
import sys
print(sys.version)

3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]

In [ ]:
pip uninstall tensorflow keras -y

Found existing installation: tensorflow 2.15.0
Uninstalling tensorflow-2.15.0:
  Successfully uninstalled tensorflow-2.15.0
Found existing installation: keras 2.15.0
Uninstalling keras-2.15.0:
  Successfully uninstalled keras-2.15.0
Note: you may need to restart the kernel to use updated packages.

In [3]:
pip install tensorflow==2.16.1

Requirement already satisfied: tensorflow==2.16.1 in .\venv\Lib\site-packages (2.16.1)
Requirement already satisfied: tensorflow-intel==2.16.1 in .\venv\Lib\site-packages (from tensorflow==2.16.1) (2.16.1)
Requirement already satisfied: absl-py>=1.0.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.15.1)
Requirement already satisfied: libclang>=13.0.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.3.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.3.2)
Requirement already satisfied: opt-einsum>=2.3.2 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.4.0)
Requirement already satisfied: packaging in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (25.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (4.25.8)
Requirement already satisfied: requests<3,>=2.21.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (2.32.5)
Requirement already satisfied: setuptools in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (80.10.2)
Requirement already satisfied: six>=1.12.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (1.14.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (1.78.0)
Requirement already satisfied: tensorboard<2.17,>=2.16 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (2.16.2)
Requirement already satisfied: keras>=3.0.0 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.13.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.31.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in .\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow==2.16.1) (1.26.4)
Requirement already satisfied: charset_normalizer<4,>=2 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in .\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (2026.2.25)
Requirement already satisfied: markdown>=2.6.8 in .\venv\Lib\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\venv\Lib\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\venv\Lib\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.1.6)
Requirement already satisfied: wheel<1.0,>=0.23.0 in .\venv\Lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.46.3)
Requirement already satisfied: rich in .\venv\Lib\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (14.3.3)
Requirement already satisfied: namex in .\venv\Lib\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.1.0)
Requirement already satisfied: optree in .\venv\Lib\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.19.0)
Requirement already satisfied: markupsafe>=2.1.1 in .\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow==2.16.1) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\venv\Lib\site-packages (from rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\venv\Lib\site-packages (from rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in .\venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow==2.16.1) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [26]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
import tensorflow
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()

In [29]:
model.compile(optimizer=opt,loss=loss,metrics=["accuracy"])

In [30]:
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [32]:
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [35]:
##set up early stopping
early_stopping_callback=EarlyStopping(monitor="val_loss",patience=10,restore_best_weights=True)

In [36]:
## train the model
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,
                  callbacks=[tensorflow_callback, early_stopping_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8541 - loss: 0.3488 - val_accuracy: 0.8470 - val_loss: 0.3689
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8596 - loss: 0.3438 - val_accuracy: 0.8595 - val_loss: 0.3526
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8626 - loss: 0.3386 - val_accuracy: 0.8580 - val_loss: 0.3412
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8622 - loss: 0.3362 - val_accuracy: 0.8570 - val_loss: 0.3464
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8643 - loss: 0.3355 - val_accuracy: 0.8570 - val_loss: 0.3573
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8631 - loss: 0.3303 - val_accuracy: 0.8585 - val_loss: 0.3495
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8646 - loss: 0.3299 - val_accuracy: 0.8640 - val_loss: 0.3436
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8635 - loss: 0.3293 - val_accuracy: 0.8605 - val_loss: 0.3392
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8654 - loss: 0.3259 - val_accuracy: 0.8460 - val_loss: 0.3738
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8681 - loss: 0.3234 - val_accuracy: 0.8530 - val_loss: 0.3544
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8659 - loss: 0.3222 - val_accuracy: 0.8615 - val_loss: 0.3476
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8686 - loss: 0.3225 - val_accuracy: 0.8620 - val_loss: 0.3478
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8679 - loss: 0.3183 - val_accuracy: 0.8615 - val_loss: 0.3497
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8712 - loss: 0.3134 - val_accuracy: 0.8540 - val_loss: 0.3624
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8720 - loss: 0.3161 - val_accuracy: 0.8555 - val_loss: 0.3711
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8717 - loss: 0.3126 - val_accuracy: 0.8535 - val_loss: 0.3674
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8740 - loss: 0.3093 - val_accuracy: 0.8580 - val_loss: 0.3584
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8729 - loss: 0.3082 - val_accuracy: 0.8510 - val_loss: 0.3822

In [37]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [38]:
%load_ext tensorboard

In [40]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 21880), started 0:03:07 ago. (Use '!kill 21880' to kill it.)

In [41]:
from tensorflow.keras.models import load_model
model=load_model("model.h5")
with open("one_hot_encoder_geography.pkl","rb") as f:
    one_hot_encoder_geography=pickle.load(f)
with open("label_encoder_gender.pkl","rb") as f:
    label_encoder_gender=pickle.load(f)
with open("scaler.pkl","rb") as f:
    scaler=pickle.load(f)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [43]:
input_data={
    "CreditScore":600,
    "Geography":"France",  
    "Gender":"Male",
    "Age":40,
    "Tenure":3,
    "Balance":60000,
    "NumOfProducts":2,
    "HasCrCard":1,
    "IsActiveMember":1,
    "EstimatedSalary":50000
}

In [44]:
geo_encoded=one_hot_encoder_geography.transform([[input_data["Geography"]]]).toarray()
geo_encoded_df=pd.DataFrame(geo_encoded,columns=one_hot_encoder_geography.get_feature_names_out(["Geography"]))
geo_encoded_df

e:\Ann_Classification\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [45]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [46]:
input_df["Gender"]=label_encoder_gender.transform(input_df["Gender"])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [47]:
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [48]:
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [50]:
prediction=model.predict(input_scaled)
prediction_proba=prediction[0][0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step

In [52]:
prediction_proba

0.0412297

In [53]:
if prediction_proba>0.5:
    print("The customer is likely to churn.")
else:
    print("The customer is unlikely to churn.")

The customer is unlikely to churn.